env:
  global:
  - BUILD_VERSION=0.1.$TRAVIS_BUILD_NUMBER
  - secure: iqu5VxI/3Y63GD5ooQl7sr8MEJ0k8HAx3Fw2I65Na3Hi5L5J6ID6GC/fpD6Lo5W7Wt4A7mPXgVlRKZpgysAXQXd+wGuQBIlKKgqdQs6UvPK71PMYiTbj1bkqNG0KMWMkz/gKL5FY3Y6V2Cz1fTp7OB1Gsj3CcScQA/50VEQuXVzWn1xl0EsaFe14eP/Qq7DrsJvBSmxHNfw+ZWm1WXb/xxM2Wp2HI/tcjnW3CUcYT9y/iFWbcE1vIqXJCX0oTAclv5oVq3kJX0Q+I2aZyi4pP3lyD9QU7/OCkhZu/uymufZs26yYXIzPrBbu+x8EjG0Do1D7n5FAIr4//443GmMey3s8nwx5CeZmx4mEHuvUDsDqbhhJ8RTk4Ug+qILge7Wx/qCl99VeTFxDnQ0NXonCGkMKus2jy2Dppl3onWVbOFpAyNIoGfcShQzLltZ0C0uLjv6PBA8hHm7kdlcqZ5FUodo7ylffgZolFmo0JXQdVVMllIr6TUG/dbMccAHra/Kuq9pfHf8U/I8xCS6jXX5Yv/h6vXWAo5/pPDiaqJj9FcqpJGHtHsUlfJvpiXGTuWAgy4oMZXTQLx24zXFK164AT/10XzQrRrJy3OsV3bNuPD3vRCScYNHS+u9o2bal3fKS2Mkav50ZCKxXMMM6OrntcnDxi7UfzhwtHlzlSDJl9X4=
sudo: false
branches:
  except:
  - /^*[0-9]/
services:
  - docker
script:
  - make build VERSION=$BUILD_VERSION
  - make test VERSION=$BUILD_VERSION
after_success:
  - make tag VERSION=$BUILD_VERSION GH_TOKEN=$BUILD_KEY

deploy:
  provider: packagecloud
  repository: "rowancarr/rpm"
  username: ""
  token: "YOUR TOKEN"
  dist: "YOUR DIST" # like 'ubuntu/precise', or 'centos/5', if pushing deb or rpms
