language: ruby
env:
  global:
  - BUILD_VERSION=0.1.$TRAVIS_BUILD_NUMBER
  - secure: nTO4C7rWnCFP3h9tdCuNGOxxREA2NyZpU7fnnOFENOhjcWuaDl5dfHbF9KQy0AHBJrDAfuOJrhccMzgL0o8fYs2DET+QDhuiJaGBnJ8DCZVQqUP8yoskReG4w/EejTe82rPoNr9mq1at/Di4K8ZQsyAbF0JYSl7QEnoPDFDtvgLsOE33IF3sE2zXNBAiv4x6MoDhmnAZe2KYddAgB8MuB+5Xg6uNo4NkbJdMD3Y9d6nck8nbMmVhuTLVkpYIt1SS4X4mV+0uBEuwkTGv/1LQLJWTtwp5Wnti0QYMqEXc0jQiNjfx0mViJ5Oq2NHt/VXrzhl3RJYFgh9UWEejYNntW3EWF+KiUVKfUkd9N/KiYhgjZqfp98y2YMhbB5Vcdf0kn4hmndumXmIfh5qJvMCQrgNjPx0RSvQZQMnyGRFYIQoDflRAX01XmmicMd43+SZDVwV9KRzSyLmhNOzltSRWsYime/I2hfair7dSiixFMp+fYgOZdFnzcIc/4tWRRL8bt9b+3ZMTO/uOiuGp2/+Sifs7eTAYtQLp73QMvdRgTYPnxU2OfFEYEAYWSz3cYNJ58LJpLze3ZZnSzHknjGyz8J4Ubgs4bOa/Qdp56D/evYPPp9OkSFZzMWD6QD6dDhg+GnasiZbUsKyDIn/mUG3iFg649xEZfUAw3ST1HaEJUqg=
  - secure: RKdLyrOffy6vCYaRpDYKGkX2tAc/OkloqgfBVSFq6wVkywxc7cofoSvK9ONM377XnEgsRmtx1wFBfl4uTtAw28IVrvqnRldfzPAn3KZxo0vwETDiJSCaNJqMvyMvV5TE88MW4lPylhmPNr94hHWMu2jCgmdGQuK8XtBApyzUjqKT3vOtNqrAT1Md6Bpvwh5NSDm4VucyrBEfh/MYA+RgXp/uN4vBxW3uMAMAPP6vkm54AqpCzlKIMv+7Hv+BB0++6qdm9CZSGkJHH6ruti2F7cW/SGBTDFay56eXteiCWrYrVMWoa03wp1FnYr12uN/L+ovAcLk8QTp/38mcQhoFBkABjBPCn655kwH8hcZj8vl1P7exeZUyT6krnbCBp8T/GDhDa+vG+nJdLvHQFHWrHED5e/R1uFqGMX1n0wEHgGqkv7o7xIaWmkaRVWFvOOPtYuJkLwgAG7xu5anP4lrRBiecWhOeC6gXyGUpTJfXBo+PPbZx1WCzwOWvx11mJpKGmISYsXD28F1MJ5zWoIwhKHdoJLWKg7JbEWNCjx5mNauN3AcL+mkEoDKEuQq0GII+IE6nGPEuYywtsCbpyj672AfHMb4dH/Y7DUb/xexBkl/XvKAMo9ey6d+75ErEVRXTu8WTJibAHjpgJyk017TV9D6qGEQnFnjPmkqVrohvsbI=
sudo: false
branches:
  except:
  - /^*[0-9]/
services:
- docker
before_install:
- gem install package_cloud
script:
- make build VERSION=$BUILD_VERSION
- make test VERSION=$BUILD_VERSION
after_success:
- make tag VERSION=$BUILD_VERSION GH_TOKEN=$BUILD_KEY
- make deploy
